[package]
name = "dance-tracker-core"
version = "0.1.0"
edition = "2024"
homepage = "https://github.com/biffjezos/dance-tracker/"

[lib]
name = "dance_tracker_engine"
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3.103"
wasm-bindgen = "0.2.126"
web-sys = { version = "0.3.103", features = ["CanvasRenderingContext2d", "HtmlCanvasElement", "HtmlVideoElement", "HtmlImageElement", "ImageData", "Window", "Document", "Element", "TextMetrics", "Performance"] }
serde = { version = "1.0.229", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
inventory = "0.3"
wgpu = "30.0.0"
pollster = "1.0.1"
bytemuck = "1.25.2"