[package]
name = "dance-tracker-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "demo"
path = "src/main.rs"

[dependencies]
js-sys = "0.3.103"
wasm-bindgen = "0.2.126"
web-sys = { version = "0.3.103", features = ["CanvasRenderingContext2d", "HtmlCanvasElement", "HtmlVideoElement", "HtmlImageElement", "ImageData", "Window", "Document", "Element", "TextMetrics", "Performance"] }
