name: Dev Build

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - run: rustup target add wasm32-unknown-unknown

      - run: cargo build
      - run: cargo build --target wasm32-unknown-unknown