export const state = {
    wasmApp: null,
    camera: null,
    nextVideoNumber: 1,
    nextMaskNumber: 1,
    nextRingsNumber: 1,
    nextGhostNumber: 1,
    nextTextNumber: 1,
    nextCompositeNumber: 1,
    cameraActivated: false,
    cameraOn: false,
    videoLayers: [],
    maskLayers: [],
    ringsLayers: [],
    ghostLayers: [],
    textLayers: [],
    compositeLayers: [],
    selectedVideoId: null,
    selectedMaskId: null,
    selectedCompositeId: null,
    outputEntryId: null,
    transportPlaying: false,
    outputResolutionIndex: 0,
    outputWidth: 320,
    outputHeight: 240
};