// src/compositor/bbox.rs

/// A single axis-aligned bounding box: half-open pixel-index bounds
/// `[x0,x1) x [y0,y1)`. See BBOX_CONVENTIONS.md for the full rationale -
/// in short, this is a conservative "region that actually matters" a node
/// reports about its own output, never an exact fit. A box larger than an
/// operation's true content extent is always safe; smaller is not.
///
/// Signed coordinates (not `u32`) so intermediate math - e.g. MOVE's
/// translation, or a negative GROW - can be computed directly and clamped
/// to the frame afterward, rather than needing saturating arithmetic at
/// every step.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Rect {
    pub x0: i32,
    pub y0: i32,
    pub x1: i32,
    pub y1: i32,
}

impl Rect {
    /// The entire frame - today's implicit behavior everywhere, and the
    /// default every operation inherits until it opts into reporting
    /// something tighter.
    pub fn full(width: u32, height: u32) -> Self {
        Self { x0: 0, y0: 0, x1: width as i32, y1: height as i32 }
    }

    /// No region at all - e.g. an offset that moves content fully
    /// off-canvas. Represented as a canonical zero-sized rect at the
    /// origin, not a marker value - `is_empty()` is what callers check.
    pub fn empty() -> Self {
        Self { x0: 0, y0: 0, x1: 0, y1: 0 }
    }

    /// True whenever the rect has zero or negative extent on either axis -
    /// covers `empty()` and any rect degenerated by an intersection with
    /// nothing left in common.
    pub fn is_empty(&self) -> bool {
        self.x1 <= self.x0 || self.y1 <= self.y0
    }

    /// The overlapping region of two rects - `Rect::empty()` if they don't
    /// overlap at all, or if either operand already is empty.
    pub fn intersect(&self, other: &Rect) -> Rect {
        if self.is_empty() || other.is_empty() {
            return Rect::empty();
        }

        let x0 = self.x0.max(other.x0);
        let y0 = self.y0.max(other.y0);
        let x1 = self.x1.min(other.x1);
        let y1 = self.y1.min(other.y1);

        if x1 <= x0 || y1 <= y0 {
            Rect::empty()
        } else {
            Rect { x0, y0, x1, y1 }
        }
    }

    /// The smallest rect containing both operands. An empty operand is
    /// ignored (returns the other operand unchanged) rather than treated
    /// as "extend to include the origin" - `empty()`'s own `(0,0,0,0)`
    /// coordinates are not a real point to union against.
    pub fn union(&self, other: &Rect) -> Rect {
        if self.is_empty() {
            return *other;
        }
        if other.is_empty() {
            return *self;
        }

        Rect {
            x0: self.x0.min(other.x0),
            y0: self.y0.min(other.y0),
            x1: self.x1.max(other.x1),
            y1: self.y1.max(other.y1),
        }
    }

    /// Expands the rect by `amount` on every side (a negative amount
    /// shrinks it instead). An empty rect stays empty - there is nothing
    /// to grow outward from. Callers that need the result bounded to the
    /// frame (e.g. BLUR) intersect the result against `Rect::full`
    /// themselves - `grow` alone does not clamp.
    pub fn grow(&self, amount: i32) -> Rect {
        if self.is_empty() {
            return *self;
        }

        Rect {
            x0: self.x0 - amount,
            y0: self.y0 - amount,
            x1: self.x1 + amount,
            y1: self.y1 + amount,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn full_covers_exactly_the_frame() {
        let r = Rect::full(4, 3);
        assert_eq!(r, Rect { x0: 0, y0: 0, x1: 4, y1: 3 });
    }

    #[test]
    fn empty_is_empty() {
        assert!(Rect::empty().is_empty());
    }

    #[test]
    fn full_is_not_empty() {
        assert!(!Rect::full(4, 4).is_empty());
    }

    #[test]
    fn a_degenerate_rect_with_equal_bounds_is_empty() {
        assert!(Rect { x0: 2, y0: 2, x1: 2, y1: 5 }.is_empty());
        assert!(Rect { x0: 2, y0: 2, x1: 5, y1: 2 }.is_empty());
    }

    #[test]
    fn intersect_of_overlapping_rects_is_the_shared_region() {
        let a = Rect { x0: 0, y0: 0, x1: 6, y1: 6 };
        let b = Rect { x0: 3, y0: 3, x1: 9, y1: 9 };
        assert_eq!(a.intersect(&b), Rect { x0: 3, y0: 3, x1: 6, y1: 6 });
    }

    #[test]
    fn intersect_of_disjoint_rects_is_empty() {
        let a = Rect { x0: 0, y0: 0, x1: 2, y1: 2 };
        let b = Rect { x0: 5, y0: 5, x1: 7, y1: 7 };
        assert!(a.intersect(&b).is_empty());
    }

    #[test]
    fn intersect_with_an_empty_operand_is_empty() {
        let a = Rect::full(10, 10);
        assert!(a.intersect(&Rect::empty()).is_empty());
        assert!(Rect::empty().intersect(&a).is_empty());
    }

    #[test]
    fn union_of_disjoint_rects_covers_both() {
        let a = Rect { x0: 0, y0: 0, x1: 2, y1: 2 };
        let b = Rect { x0: 5, y0: 5, x1: 7, y1: 7 };
        assert_eq!(a.union(&b), Rect { x0: 0, y0: 0, x1: 7, y1: 7 });
    }

    #[test]
    fn union_with_an_empty_operand_returns_the_other_operand_unchanged() {
        // The load-bearing edge case: an empty operand must not pull the
        // union toward the origin (0,0) the way a naive min/max over
        // empty's own (0,0,0,0) coordinates would.
        let a = Rect { x0: 4, y0: 4, x1: 8, y1: 8 };
        assert_eq!(a.union(&Rect::empty()), a);
        assert_eq!(Rect::empty().union(&a), a);
    }

    #[test]
    fn grow_expands_every_side_by_the_given_amount() {
        let r = Rect { x0: 4, y0: 4, x1: 8, y1: 8 };
        assert_eq!(r.grow(2), Rect { x0: 2, y0: 2, x1: 10, y1: 10 });
    }

    #[test]
    fn grow_of_an_empty_rect_stays_empty() {
        assert!(Rect::empty().grow(5).is_empty());
    }

    #[test]
    fn growing_past_the_frame_is_not_clamped_by_grow_itself() {
        // grow() alone doesn't clamp - callers intersect against
        // Rect::full themselves (see BLUR's output_bbox in Phase 2).
        let r = Rect { x0: 0, y0: 0, x1: 4, y1: 4 };
        let grown = r.grow(10);
        assert_eq!(grown, Rect { x0: -10, y0: -10, x1: 14, y1: 14 });

        let clamped = grown.intersect(&Rect::full(4, 4));
        assert_eq!(clamped, Rect::full(4, 4));
    }
}
