name: Rust Debug Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: engine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Cargo check
        run: cargo check

      - name: Debug build
        run: cargo build

      - name: WASM debug build
        run: cargo build --target wasm32-unknown-unknown