name: Deploy static content to Pages

on:
  push:
    branches: ["dev"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  changes:
    runs-on: ubuntu-latest
    outputs:
      rust: ${{ steps.filter.outputs.rust }}
      wasm: ${{ steps.filter.outputs.wasm }}
      ui: ${{ steps.filter.outputs.ui }}

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            rust:
              - 'engine/src/**'
              - 'engine/Cargo.toml'
              - 'engine/Cargo.lock'

            wasm:
              - 'engine/src/**'
              - 'engine/Cargo.toml'
              - 'engine/Cargo.lock'
              - 'engine/**'

            ui:
              - 'ui/**'


  build-wasm:
    needs: changes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            engine/target
          key: rust-${{ runner.os }}-${{ hashFiles('engine/Cargo.lock') }}

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build WASM
        env:
          BUILD_COMMIT: ${{ github.sha }}
        run: wasm-pack build engine --target web

      - name: Upload WASM
        uses: actions/upload-artifact@v4
        with:
          name: wasm-package
          path: engine/pkg


  deploy:
    needs:
      - build-wasm

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Download WASM package
        uses: actions/download-artifact@v4
        with:
          name: wasm-package
          path: ui/engine/pkg

      - name: Write build metadata
        run: echo "${GITHUB_SHA}" > ui/build-version.txt

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./ui

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v5